# # catpuccin mocha lavender
# [colors]
# background=1e1e2edd
# text=cdd6f4ff
# prompt=bac2deff
# placeholder=7f849cff
# input=cdd6f4ff
# match=b4befeff
# selection=585b70ff
# selection-text=cdd6f4ff
# selection-match=b4befeff
# counter=7f849cff
# border=b4befeff

# # catpuccin mocha blue
# [colors]
# background=1e1e2edd
# text=cdd6f4ff
# prompt=bac2deff
# placeholder=7f849cff
# input=cdd6f4ff
# match=89b4faff
# selection=585b70ff
# selection-text=cdd6f4ff
# selection-match=89b4faff
# counter=7f849cff
# border=89b4faff

# aardvark blue 
[colors]
background=102040ee
text=ddddddff
prompt=bfdbfeff
placeholder=
input=ddddddff
match=007accff
selection=bfdbfeff
selection-text=000033ff
selection-match=000033ff
counter=
border=
